{% set version = "0.28.0" %}

package:
  name: murmurhash
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/murmurhash/murmurhash-{{ version }}.tar.gz
  sha256: 651137ed3e1169342c9edade454f3beb7fcdf28d4ad1ac232725237eaf442d9a

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - msinttypes  # [win and py<35]
  run:
    - python

test:
  imports:
    - murmurhash

about:
  home: https://github.com/explosion/murmurhash
  license: MIT
  license_file: LICENSE
  summary: Cython bindings for MurmurHash2

extra:
  recipe-maintainers:
    - rmax
